# Levantar el ambiente: docker-compose up
# Para reiniciar todo el ambiente: docker-compose down -v
# este comando es para cuando hay bugs de conexion
version: '3.3'
services:
  mysql_db:
    container_name: artmin_mysql
    image: mysql:5.7
    restart: always
    environment:
      # Nombre de la base de datos
      MYSQL_DATABASE: 'artmin'
      # Usuario de la base de datos
      MYSQL_USER: 'oscar'
      # Password de la base de datos
      MYSQL_PASSWORD: '12345678'
      # Password del root
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '30601:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql
# Names our volume
volumes:
  mysql-volume:
